"""create_chemistry_saves_table

Revision ID: 102219d86db6
Revises: c3d4e5f6a7b8
Create Date: 2026-08-04 16:12:13.588860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102219d86db6'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemistry_saves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_autosaved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemistry_saves_experiment_id'), 'chemistry_saves', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_chemistry_saves_idempotency_key'), 'chemistry_saves', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_chemistry_saves_simulation_id'), 'chemistry_saves', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_chemistry_saves_status'), 'chemistry_saves', ['status'], unique=False)
    op.create_index(op.f('ix_chemistry_saves_updated_at'), 'chemistry_saves', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chemistry_saves_user_id'), 'chemistry_saves', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemistry_saves_user_id'), table_name='chemistry_saves')
    op.drop_index(op.f('ix_chemistry_saves_updated_at'), table_name='chemistry_saves')
    op.drop_index(op.f('ix_chemistry_saves_status'), table_name='chemistry_saves')
    op.drop_index(op.f('ix_chemistry_saves_simulation_id'), table_name='chemistry_saves')
    op.drop_index(op.f('ix_chemistry_saves_idempotency_key'), table_name='chemistry_saves')
    op.drop_index(op.f('ix_chemistry_saves_experiment_id'), table_name='chemistry_saves')
    op.drop_table('chemistry_saves')
    # ### end Alembic commands ###
